workspace:
  base: /drone
  path: /workdir

pipeline:
  build:
    image: multiarch/crossbuild
    environment:
      - ARCH=arm
      - CROSS_COMPILE=arm-linux-gnueabihf-
    commands:
      - make multi_v7_defconfig
      - make -j8
      - ls -al arch/arm/boot/
    when:
      event: push
